"""update font ocr model, move the index to text column

Revision ID: f257317c2479
Revises: cf6709fa0c6e
Create Date: 2019-12-31 17:55:58.740373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f257317c2479'
down_revision = 'cf6709fa0c6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_font_records_text'), 'font_records', ['text'], unique=False)
    op.drop_index('ix_font_records_code', table_name='font_records')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_font_records_code', 'font_records', ['code'], unique=False)
    op.drop_index(op.f('ix_font_records_text'), table_name='font_records')
    # ### end Alembic commands ###
